Development
RWTH-EBC/TEASER pull request #689
Opened 2021-06-09 08:50 UTC by MartinRaetz

solves #688

2021-06-09 08:51 UTC, MartinRaetz commented
I suggest to "squash and merge" - objections?

2021-06-14 08:03 UTC, DaJansenGit requested changes
Some minor things. Mostly version raise of aixlib version

2021-06-14 08:03 UTC, DaJansenGit commented on teaser/logic/buildingobjects/calculation/aixlib.py
> +        self.version = "0.10.7"
shouldn't this be raised to 1.0.0?

2021-06-14 08:03 UTC, DaJansenGit commented on teaser/logic/buildingobjects/calculation/ibpsa.py
> +            "AixLib": "0.10.7",
should be 1.0.0

2021-06-16 12:09 UTC, MartinRaetz reviewed
Some changes have been due to prior branches merged to the development. 
Thank you for noticing the improvements!

2021-06-16 12:09 UTC, MartinRaetz commented on teaser/logic/buildingobjects/calculation/ibpsa.py
> +            "AixLib": "0.10.7",
correct!

2021-06-16 12:09 UTC, MartinRaetz commented on teaser/data/input/inputdata/MaterialTemplates.json
> +        "density": 1.184,
I think this was faulty for Air. Though this is a change done in one of the branches merged into the development. I think the development is correct.

2021-06-16 12:09 UTC, MartinRaetz commented on teaser/data/output/aixlib_output.py
> +import shutil
Thank you for noticing! I changed all occurences I could found.

2021-06-16 12:09 UTC, MartinRaetz commented on teaser/logic/buildingobjects/calculation/aixlib.py
> +        self.version = "0.10.7"
Thank you! Correct!

2021-06-16 12:44 UTC, DaJansenGit approved these changes

2021-06-16 12:44 UTC, DaJansenGit commented
Thanks for the changes! :)

2021-06-16 15:41 UTC, merged