Issue679 interzonal elements, soil temperature, and interior geometry estimation
RWTH-EBC/TEASER pull request #785
Opened 2024-11-17 16:17 UTC by PGorzalka

Finally, I was able to finish the work on issue #679 
@DaJansenGit thanks for your support!

Changes mainly encompass the work mentioned in [this paper](https://doi.org/10.3384/ecp204577):
- building up on [changes already implemented via IBPSA merge](https://github.com/ibpsa/modelica-ibpsa/issues/1744), some adaptations for non-constant soil temperature
  - Soil temperature can now be a constant, a sine, or specified in an additional input file
  - Project parameter defines what is chosen
- Interzonal elements (that is, building elements that connect two zones)
  - New building element object types `InterzonalWall`, `InterzonalCeiling` and `InterzonalFloor`
  - Due to current convention, building elements have only one parent thermal zone. This is why an interzonal element has to be created twice (once for each zone it borders) and has subsequently two representations in TEASER
  - Export to AixLib using the new FiveElements RC model there, making sure that only one of the two representations is actually considered in simulation.
  - If exported to an AixLib model with less elements, interzonal building elements will be lumped into interior or exterior walls depending on the zones' properties
  - Option to load layers in reversed order to make sure borders are correctly represented on both sides
  - Possibility to place insulation layer not necessarily on the outside (making sure that it is placed correctly for both representations of the same interzonal element)
- New method(s) to estimate interior geometry
  -  Introduced as string parameter of a Building object
  - `'typical_minus_outer'` sets length of inner walls = 2 * typical length * height of floors + 2 * typical width * height of floors - length of outer or interzonal walls
  - `'typical_minus_outer_extended'` like `'typical_minus_outer'`, but also considers that
     a) a non-complete "average room" reduces its circumference proportional to the square root of the area
     b) rooftops, windows and ground floors (= walls with border to soil) may have a vertical share
  - Number and height of floors can now be set as zone parameters
- Included everything to JSON input/output
- Example 11 covering all three (soil temperature, interzonals, new interior mass estimation) and creates ASHRAE140 test case 960
- Tests covering all three (soil temperature, interzonals, new interior mass estimation). Note: I did not change the old test functions, although the GitHub diff says I did. I just duplicated and adapted them.

Additional minor stuff:
- Custom multizone template, so boundary conditions can be adapted more easily
- two missing `each`s in `AixLib.Fluid.Pools.BaseClasses.AirFlowMoistureToROM` caused OM to fail -> fixed
- weather data path can be specified starting with `modelica:` to reference to existing Modelica resources
- Some fixes to buildingelement.py to make it more resilient against minor bugs
- Corrected some docstring typos
- Heavily reduced length of code in RC parameter calculation. Adaptations there were necessary due to the reversed layers of interzonal elements, but it was basically impossible to debug before.

Missing:
- Test Case 960 was not actually tested against standard results because the weather file provided in AixLib (AixLib\Resources\weatherdata\ASHRAE140.mos) does not contain the weather data provided by the standard. 
- Reference the paper in Readme?
- version count, also in example json inputs
- Project docstring that recommends `For AixLib you should always use 2 elements!!!` -> what should be written there?

See also [PR 1546 in AixLib](https://github.com/RWTH-EBC/AixLib/pull/1546)

Looking forward to your feedback on the changes!

2024-12-08 17:03 UTC, PGorzalka commented
@DaJansenGit added your commits to the CI branch and renamed the ground temperature selector in the records as you suggested in the AixLib PR

2025-02-03 18:31 UTC, DaJansenGit requested changes
Thanks for this huge adjustments and new features in TEASER. I have some minor remarks and I recognized that the CI failed. But only for python 3.12.

Furthermore, I would like to check if existing results for all examples all stay the same as this is currently not done via the CI in TEASER. 

Also I have to say that I didn't check if the implementation for the R/C calculation are correctly as these are a lot of changes. If the existing models all pass together with your paper I guess this is fine.

2025-02-03 18:31 UTC, DaJansenGit commented on teaser/examples/e11_include_adjacent_zones_and_varying_soil_temps.py
> +    for variation in ['A', 'B', 'C', 'D']:
Maybe add more information about what these variants are. You could add the table from the paper?

2025-02-03 18:31 UTC, DaJansenGit commented on teaser/examples/examplefiles/ASHRAE140_600.json
> +            "version": "4.0.0"
nice catch, that has been there for a while :D

2025-02-03 18:31 UTC, DaJansenGit commented on teaser/data/output/modelicatemplate/AixLib/AixLib_Multizone
> +        redeclare package Medium = ${"Modelica.Media.Air.DryAirNasa" if any([tz.use_conditions.with_heating is False for tz in bldg.thermal_zones]) else "Modelica.Media.Air.SimpleAir"},
This is a nice change. Should also prevent model crashes in the future with normal exports.

2025-02-03 18:31 UTC, DaJansenGit commented on teaser/data/input/teaserjson_input.py
> +            try:
I have to admit that I do not really like the the try/except approach here. I would suggest to use `get` functionality to retrieve default values if the key could not be found. What do you think about this? If you agree please change this also at the other occurenes in this function

2025-02-03 18:31 UTC, DaJansenGit commented on teaser/logic/buildingobjects/buildingphysics/buildingelement.py
> +        if not type_element_key:
I couldn't find a point in the code where you are actually using the `type_element_key`/`key_str` argument. Am I missing something or is this a relict and can be removed?

If not, I would suggest to use the same name `type_element_key` for both arguments.

2025-02-03 18:31 UTC, DaJansenGit commented on teaser/data/input/buildingelement_input_json.py
> +def load_type_element_by_key(element, key_str, data_class,
I couldn't find a point in the code where you are actually using the type_element_key/key_str argument. Am I missing something or is this a relict and can be removed?

If not, I would suggest to use the same name type_element_key for both arguments.

(Left the same commend in buildingelement.py)

2025-02-03 21:25 UTC, PGorzalka commented on teaser/examples/e11_include_adjacent_zones_and_varying_soil_temps.py
> +    for variation in ['A', 'B', 'C', 'D']:
I added a reference to the Table. As the paper is openly available, I think that should be fine.

2025-02-03 22:10 UTC, PGorzalka commented on teaser/logic/buildingobjects/buildingphysics/buildingelement.py
> +        if not type_element_key:
Indeed, it has vanished from the code and also from our paper. In fact, I needed it for the additional variations E and F that I calculated for my dissertation (which has finally been published :D see Table 4.2 [here](https://publications.rwth-aachen.de/record/998671)). I consider it's a nice feature if you want to load some element that does not match the current archetype. 

So I implemented your second suggestion. I don't know if something was changed in the meantime, but using this needs to have year and construction being keyword arguments. Hope it's fine like I did it now.
As it's not tested at the moment, I also added it to the example to make sure it's not "forgotten" in the future.

2025-02-03 22:11 UTC, PGorzalka commented on teaser/data/input/buildingelement_input_json.py
> +def load_type_element_by_key(element, key_str, data_class,
done

2025-02-03 22:37 UTC, PGorzalka commented
Regarding the CI failing on Python 3.12, does this only happen for this PR or generally?

2025-03-12 20:03 UTC, PGorzalka commented
@DaJansenGit is there anything I can do here?

2025-03-13 14:23 UTC, DaJansenGit commented on teaser/logic/buildingobjects/buildingphysics/buildingelement.py
> +        if not type_element_key:
Thank you for the changes. The solution is fine for me.

2025-03-13 14:24 UTC, DaJansenGit commented on teaser/examples/e11_include_adjacent_zones_and_varying_soil_temps.py
> +    for variation in ['A', 'B', 'C', 'D']:
Thanks for adding the changes and happy that I could help :)

2025-03-13 14:25 UTC, DaJansenGit commented on teaser/data/input/teaserjson_input.py
> +            try:
Thanks for adding the changes and I'm happy that I could help :)

2025-03-13 14:56 UTC, DaJansenGit commented
Hey, sorry it's taken so long, I've been down a rabbit hole for the last few weeks writing my thesis.

I looked it up and this seems to be a common problem due to the new floating point calculation in Python 3.12. You're just the unfortunate person doing the first PR since we implemented the tests for 3.12. :D I'll make a fix in the main branch, add it to this branch and then we can proceed.

2025-03-13 17:11 UTC, PGorzalka commented
Thank you @DaJansenGit  :D 
Hope your thesis is going well!
But I cannot take that honor, privileges are missing ;)

2025-03-14 07:30 UTC, merged